version: '2'

services:
  
  hub:
    image: selenium/hub:3.8.1-chlorine
    environment:
      - JAVA_OPTS=-Xmx4G
      - LOGSPOUT=ignore
      - shm_size=512MB
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - NODE_MAX_INSTANCE=5
      - NODE_MAX_SESSION=5
    expose:
      - 4444
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome:3.8.1-chlorine
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox:3.8.1-chlorine
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    networks:
      - selenium-grid

  test-gc:
    build: robot
    command: -v BROWSER:gc -d /out /tests/
    volumes:
      - ./robot/tests_robot:/tests
      - ./results/gc:/out
    depends_on:
      - chrome
    networks:
      - selenium-grid

  test-ff:
    build: robot
    command: -v BROWSER:ff -d /out /tests/
    volumes:
      - ./robot/tests_robot:/tests
      - ./results/ff:/out
    depends_on:
      - firefox
    networks:
      - selenium-grid

networks:
  selenium-grid:
